# Generated by Django 5.1 on 2025-04-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
