# Generated by Django 5.1 on 2025-04-19 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PSYCHO", "Психологическая"),
                            ("FINANCIAL", "Материальная"),
                            ("VOLUNTEER", "Волонтерская"),
                        ],
                        max_length=100,
                        verbose_name="Тип помощи",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("ONLINE", "Онлайн"), ("OFFLINE", "Оффлайн")],
                        max_length=100,
                        verbose_name="Формат помощи",
                    ),
                ),
                ("text", models.TextField(verbose_name="Описание")),
                ("address", models.TextField(verbose_name="Адрес")),
                ("contacts", models.TextField(verbose_name="Контакты")),
                ("time", models.TextField(verbose_name="Время")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Новая"),
                            ("IN_PROGRESS", "В работе"),
                            ("DONE", "Завершена"),
                        ],
                        default="NEW",
                        max_length=100,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Время создания"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(blank=True, default=None, null=True, verbose_name="Рейтинг"),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Активная"),
                            ("SUCCESS", "Успешная"),
                            ("CLOSE", "Закрыта"),
                        ],
                        default="ACTIVE",
                        max_length=100,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Время создания"),
                ),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="calls.call",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Отклик",
                "verbose_name_plural": "Отклики",
            },
        ),
    ]
