# Generated by Django 5.1 on 2025-04-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="Ссылка"),
        ),
    ]
