# Generated by Django 5.1 on 2025-04-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_notification_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="link",
            field=models.TextField(blank=True, null=True, verbose_name="Ссылка"),
        ),
    ]
