# Generated by Django 5.2 on 2025-04-19 11:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_alter_notification_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ("-created_at",), "verbose_name": "Уведомление", "verbose_name_plural": "Уведомления"},
        ),
    ]
